# Generated by Django 2.2.12 on 2020-05-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20200519_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionalsalud',
            name='centro_salud',
            field=models.CharField(default=-1.0, max_length=50),
            preserve_default=False,
        ),
    ]
