# Generated by Django 2.2.12 on 2020-07-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_remove_profesionalsalud_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionalsalud',
            name='rol',
            field=models.IntegerField(null=True),
        ),
    ]
