# Generated by Django 2.2.12 on 2020-07-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_profesionalsalud_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionalsalud',
            name='rol',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
