# Generated by Django 2.2.12 on 2020-07-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_profesionalsalud_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionalsalud',
            name='rol',
            field=models.CharField(max_length=25),
        ),
    ]
