# Generated by Django 2.2.12 on 2020-07-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_auto_20200709_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionalsalud',
            name='rol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
