# Generated by Django 2.2.12 on 2020-07-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_auto_20200709_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionalsalud',
            name='rol',
        ),
    ]
